name: "Build and Test"
on:
  workflow_call:
    inputs:
      # Docker image to use for the test environment
      container-image:
        type: string
        required: true
      # Init script that should be executed right after checkout.
      init-script:
        type: string
        required: false
      # Tests script to launch integration (whatever) tests with DFX environment
      # If skipped tests would not be launched
      test-script:
        type: string
        required: false
      # Force skipping test-script if it is provided
      # Use this for advanced configuration
      skip-test:
        type: boolean
        required: false
      # Do not fail on audit warnings only of critical errors
      audit-allow-warnings:
        type: boolean
        required: false
      # Name of the github artfact to upload for reusing in next jobs
      # If not defined -> would skip artifact uploading
      output-artifact:
        type: string
        required: false
      # Script that builds artifact files and put them into .artifact directory
      artifact-script:
        type: string
        required: false
      # Additional artifact logic to run before tests
      artifact-pre-script:
        type: string
        required: false
      enable-target-cache:
        type: boolean
        required: false
      disable-cache:
        type: boolean
        required: false
      rs-skip-clippy:
        type: boolean
        required: false
      git-fetch-depth:
        type: string
        required: false
      cargo-clippy-extra-args:
        type: string
        required: false
        default: ''
    secrets:
      gh_token:
        required: true
      gh_login:
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  assemble-and-test:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.container-image }}
      credentials:
        username: ${{ secrets.gh_login }}
        password: ${{ secrets.gh_token }}

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.gh_token }}
          fetch-depth: ${{ inputs.git-fetch-depth }}

      - name: "Init script"
        if: ${{ inputs.init-script }}
        run: ${{ inputs.init-script }}

      - name: Checking for a test tag
        id: tag
        run: |
          TT=""
          if [ "$GITHUB_REF_TYPE" = "tag" ] && [ "${GITHUB_REF_NAME%-test}" != "$GITHUB_REF_NAME" ]; then TT="true"; fi
          echo "test=$TT" >> $GITHUB_OUTPUT

      - uses: Swatinem/rust-cache@v2
        if: ${{ ! inputs.disable-cache }}
        with:
          shared-key: ${{ github.repository }}
          cache-targets:  ${{ inputs.enable-target-cache }}
          save-if: ${{ github.ref_type != 'tag' }}

      - name: "Audit prepare config, adding ignores from file ./AUDIT_IGNORE if any"
        if: ${{ ! steps.tag.outputs.test }}
        id: audit
        run: |
          AUDIT_IGNORE=$(cat AUDIT_IGNORE  2>/dev/null | grep RUSTSEC | awk '$0="--ignore "$0' ORS=" ")
          echo "::set-output name=ignore::$AUDIT_IGNORE"
          echo "::set-output name=w::$(if [ "${{ inputs.audit-allow-warnings }}" = "true" ]; then echo ""; else echo " -D warnings "; fi)"

      - name: "Audit"
        if: ${{ ! steps.tag.outputs.test }}
        uses: actions-rs/cargo@v1
        with:
          command: audit
          args: ${{ steps.audit.outputs.w }} ${{ steps.audit.outputs.ignore }}
          
      - name: "Checking code format"
        if: ${{ ! steps.tag.outputs.test }}
        run: cargo fmt --all --check

      - name: "Checking code style"
        if: ${{ ! inputs.rs-skip-clippy && ! steps.tag.outputs.test}} 
        run: cargo clippy --all-features --all-targets ${{ inputs.cargo-clippy-extra-args }}

      - name: "Current environment"
        run: |
          env

      - name: "Artifact initialization"
        if: ${{ inputs.output-artifact }}
        run: |
          rm -rf .artifact
          mkdir  .artifact
          ${{ inputs.artifact-pre-script }}

      - name: "Running test script"
        if: ${{ inputs.test-script && ! inputs.skip-test && ! steps.tag.outputs.test }}
        run: ${{ inputs.test-script }}

      - name: "Preparing artifact files"
        if: ${{ inputs.output-artifact }}
        run: |
          ${{ inputs.artifact-script }}

          echo "Artifact content:"
          ls -laR .artifact

      - name: "Uploading artifact: ${{ inputs.output-artifact }}"
        if: ${{ inputs.output-artifact }}
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          retention-days: 3
          name: ${{ inputs.output-artifact }}
          path: .artifact/*
      
      - name: "Removing wasm modules from target if any"
        run: rm -f target/wasm32-unknown-unknown/release/*.wasm
