name: "Update cargo version/tag"
on:
  workflow_call:
    inputs:
      toml_file:
        type: string
        required: false
    secrets:
      gh_token:
        required: true

jobs:
  bump-version-tag:
    runs-on: ubuntu-latest

    steps:
      - run: |
          sudo apt-get install -y node-semver

      - name: "Infer Cargo.toml"
        id: toml
        run: |
          CT="./Cargo.toml"
          if [ ! -z "${{ inputs.toml_file }}" ]; then CT="${{ inputs.toml_file }}"; fi
          echo "path=$CT" >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: recursive
          token: ${{ secrets.gh_token }}

      - name: "Prepare new version if any"
        id: version
        run: |
          NEW_V=""
          beginswith() { case $1 in "$2"*) true;; *) false;; esac; }

          TOML="${{ steps.toml.outputs.path }}"
          
          V_TOML=$(awk -F= '{gsub(/[ \t]+/, "", $1); gsub(/[ \t"]+/, "", $2); if($1 == "version"){print $2}}' $TOML)
          V_GIT=$(git describe --tag)

          # Assuming that we tag each version in git
          # If toml version was not changed manually 
          # expecting git tag like "v1.1.1-ab8d" and toml version like "1.1.1"

          echo "now=$V_TOML" >> $GITHUB_OUTPUT

          if beginswith $V_GIT "v$V_TOML" ; then
            echo "Toml version $V_TOML matches $V_GIT"
            if [ "$V_GIT" != "v$V_TOML" ]; then
              echo "New version: $NEW_V"
              NEW_V=$(semver -p -i patch $V_TOML)
              echo "new=$NEW_V" >> $GITHUB_OUTPUT
            fi
          else
            echo "Toml version was changed manually"
            echo "tag=v$V_TOML" >> $GITHUB_OUTPUT
          fi

      - name: "Updating cargo version"
        if: ${{ steps.version.outputs.new && github.ref_type == 'branch' && github.ref == 'refs/heads/main' }}
        run: |
          TOML="${{ steps.toml.outputs.path }}"
          sed -i -E "s/version\s*=\s*\"${{ steps.version.outputs.now }}\"/version = \"${{ steps.version.outputs.new }}\"/" $TOML

      - name: Commit changes
        if: ${{ steps.version.outputs.new && github.ref_type == 'branch' && github.ref == 'refs/heads/main' }}
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: GitHub Actions
          committer_email: actions@github.com
          message: "Update package version ${{ steps.version.outputs.now }} -> ${{ steps.version.outputs.new }}"
          tag: v${{ steps.version.outputs.new }}
          add: '*.toml'

      - name: Bump tag only
        if: ${{ steps.version.outputs.tag && github.ref_type == 'branch' && github.ref == 'refs/heads/main' }}
        uses: anothrNick/github-tag-action@1.36.0
        env:
          CUSTOM_TAG: ${{ steps.version.outputs.tag }}
          GITHUB_TOKEN: ${{ secrets.gh_token }}
