name: "Deploy cloud run"
on:
  workflow_call:

    inputs:
      gcp_project:
        type: string
        required: true
      image:
        type: string
        required: true
      service:
        type: string
        required: true
      timeout:
        type: string
        required: false
      region:
        type: string
        required: false

    secrets:
      gcp_deploy_token:
        required: true

jobs:
  cloud-run:
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.gcp_deploy_token }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: "Deploy cloud run -> ${{ inputs.service }} "
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          project_id: ${{ inputs.gcp_project }}
          service: ${{ inputs.service }}
          timeout: ${{ inputs.timeout }}
          region: ${{ inputs.region }}
          suffix: run-${{ github.run_number }}
          image: ${{ inputs.image }}

      - name: "Services URLs"
        run: |
          gcloud run --project ${{ inputs.gcp_project }} services list --platform managed --format 'table(metadata.name, status.url)'
          