name: "DFX upgrade check"
on:
  workflow_call:
    inputs:
      # Script that will be called with arguments
      latest-image:
        type: string
        required: true
      upgrade-script:
        type: string
        required: true
      input-artifact:
        type: string
        required: true
      skip-check:
        type: boolean
        required: false
    secrets:
      gh_token:
        required: true
      gh_login:
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  assemble-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      
      - name: Login to Github Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ secrets.gh_login }}
          password: ${{ secrets.gh_token }}

      - name: Checkout repository and submodules
        if: ${{ ! inputs.skip-check }}
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.gh_token }}

      - name: "Downloading artifact: ${{ inputs.input-artifact }}"
        if: ${{ ! inputs.skip-check }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.input-artifact }}
          path: ./.artifact

      - name: "Artifact content"
        if: ${{ ! inputs.skip-check }}
        run: |
          ls -laR ./.artifact

      - name: Running upgrade script
        if: ${{ ! inputs.skip-check }}
        run: |
          docker run -v $GITHUB_WORKSPACE:/workspace/project/ \
          -e ARTIFACT_DIR=/workspace/project/.artifact \
          --entrypoint /workspace/project/${{ inputs.upgrade-script }} \
          ${{ inputs.latest-image }}
