name: Publish wrapped artifacts as docker package on GH
on:
  workflow_call:
    inputs:
      # Github artifact that was produced by previous job.
      # Expecting not to have any nested folders inside artifact
      input-artifact:
        type: string
        required: true
      push-image:
        type: boolean
        required: true
      output-image-name:
        type: string
        required: true
      output-image-tag:
        type: string
        required: true
        
    secrets:
      gh_token:
        required: true
      gh_login:
        required: true

jobs:
  publish-wrapped-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Github Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ secrets.gh_login }}
          password: ${{ secrets.gh_token }}

      - name: "Downloading artifact: ${{ inputs.input-artifact }}"
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.input-artifact}}
          path: ./artifact
          
      - name: Wrapped files directory structure
        run: ls -R ./artifact

      - name: Checkout template repo
        uses: actions/checkout@v3
        with:
          repository: infinity-swap/.github
          path: self-workspace

      - name: "Wrap up in image: ${{ inputs.output-image-name }}:${{ inputs.output-image-tag }}"
        uses: docker/build-push-action@v2
        with:
          push: ${{ inputs.push-image }}
          context: ./artifact
          file: self-workspace/Dockerfile.wrapper
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ inputs.output-image-name }}:${{ inputs.output-image-tag }}
